# Generated by Django 5.1 on 2024-08-21 14:11

import django.core.validators
import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [

    ]

    operations = [

    ]
