# Generated by Django 5.1 on 2024-08-21 17:24

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles/pet_photos/', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
